# 🔑 Identificação do projeto
sonar.projectKey=DiegoDeAssisDev_poc-sonar-codereview-ia
sonar.organization=diegodeassisdev
sonar.projectVersion=1.0

# 📁 Onde está o código fonte (Flutter)
sonar.sources=lib

# 🧪 Testes
sonar.tests=test

# 🚫 Exclusões (SUPER IMPORTANTE)
sonar.exclusions=\
**/*.g.dart,\
**/*.freezed.dart,\
**/*.gen.dart,\
**/*.config.dart,\
**/*.mocks.dart,\
**/build/**,\
**/.dart_tool/**,\
**/.idea/**,\
**/.vscode/**,\
**/ios/**,\
**/android/**,\
**/macos/**,\
**/linux/**,\
**/windows/**,\
**/web/**,\
**/coverage/**

# # 📊 Coverage (opcional, mas recomendado)
# sonar.dart.lcov.reportPaths=coverage/lcov.info

# 🔎 Encoding
sonar.sourceEncoding=UTF-8